# Generated by Django 4.2.5 on 2023-10-05 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applab06', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(default=datetime.datetime(2023, 10, 5, 7, 42, 56, 14979, tzinfo=datetime.timezone.utc), upload_to='media/images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
